use_frameworks!

platform :ios, '9.0'

target 'UMShareTool_Example' do
  pod 'UMShareTool', :path => '../'

  target 'UMShareTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
